### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.Versioned

### ISSUE THREAD

**Issue by jiluhu** [lenve/vhr#110]
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/Versioned
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_92]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_92]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_92]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_92]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_92]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_92]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_92]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_92]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_92]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_92]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_92]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_92]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_92]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_92]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_92]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:641) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	... 25 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.Versioned
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_92]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_92]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_92]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_92]
	... 41 common frames omitted

**Comment by lenve** [comment]
maven依赖没有下载全

**Comment by lenve** [comment]
可以参考这个，https://mp.weixin.qq.com/s/6PPYwrNestz-gvmB4ZkAqQ
