### ISSUE TITLE
运行的时候数据库报错，哪个大佬知道怎么弄呀？我用其它UI客户端都能连接数据库

### ISSUE THREAD

**Issue by yuandoudou928** [lenve/vhr#272]
2021-05-02 16:48:35.248 ERROR 38196 --- [eate-1016408627] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql:rm-2vcpw0chzu2bwo6x2fo.mysql.cn-chengdu.rds.aliyuncs.com:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, errorCode 0, state null

java.sql.SQLException: connect error, url jdbc:mysql:rm-2vcpw0chzu2bwo6x2fo.mysql.cn-chengdu.rds.aliyuncs.com:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai, driverClass com.mysql.cj.jdbc.Driver
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1627) ~[druid-1.1.10.jar:1.1.10]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468) ~[druid-1.1.10.jar:1.1.10]

**Comment by yuandoudou928** [comment]
已解决
