### ISSUE TITLE
求大神解决一下导入maven项目的错误

### ISSUE THREAD

**Issue by shangpenghui123456789** [lenve/vhr#79]
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.IllegalArgumentException: XNIO001001: No XNIO provider found
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:155) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.sang.HrserverApplication.main(HrserverApplication.java:16) [classes/:na]
Caused by: java.lang.IllegalArgumentException: XNIO001001: No XNIO provider found
	at org.xnio.Xnio.doGetInstance(Xnio.java:270) ~[xnio-api-3.3.8.Final.jar:3.3.8.Final]
	at org.xnio.Xnio.getInstance(Xnio.java:203) ~[xnio-api-3.3.8.Final.jar:3.3.8.Final]
	at io.undertow.websockets.jsr.UndertowContainerProvider.getDefaultContainer(UndertowContainerProvider.java:90) ~[undertow-websockets-jsr-1.4.25.Final.jar:1.4.25.Final]
	at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:63) ~[undertow-websockets-jsr-1.4.25.Final.jar:1.4.25.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:263) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:153) ~[undertow-servlet-1.4.25.Final.jar:1.4.25.Final]
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.createDeploymentManager(UndertowServletWebServerFactory.java:284) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getWebServer(UndertowServletWebServerFactory.java:208) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:152) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	... 8 common frames omitted

Process finished with exit code 1

**Comment by yangmeiooo** [comment]
你idea加载项目的时候,import hrserver的.iml文件，这样你的maven会去加载相应的依赖。
